### ISSUE TITLE
No "data" element in my Heartbeat

### ISSUE THREAD

**Issue by Retrospected** [EDelsman/com.coulisse.motionblinds#2]
I've been testing this app to use with Brel blinds, which essentially should be the same system as Motion Blinds.
It seems to work just fine however in the response to the Heartbeat, my hub does not have the "data" element including the numberOfDevices.

```
[log] 2021-11-23 11:17:26 [MotionBlinds] {
  msgType: 'Heartbeat',
  mac: '<REMOVED>',
  deviceType: '02000001',
  msgID: '20211123121720079',
  token: '<REMOVED>'
}
/motion/motion.js:456
        if (gateway.nrDevices != msg.data.numberOfDevices) { // if device count changed, get new list

TypeError: Cannot read property 'numberOfDevices' of undefined
    at MotionDriver.onHeartbeat (/motion/motion.js:456:43)
    at MotionDriver.onMessage (/motion/motion.js:414:18)
    at MotionDriver.<anonymous> (/motion/motion.js:202:62)
    at Socket.emit (events.js:311:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
```

**Comment by EDelsman** [comment]
Hi,

 I saw the crash reports and was wondering where they were coming from.
This explains a lot. Do you have documentation for the brel to see if there
are more differences? I can circumvent the crash (it tries to see if new
devices were added) but I expect there may be other difference too.

Kind regards,
Edwin

**Comment by EDelsman** [comment]
PS. can you turn on full logging in the app settings, restart the app and send me a diagnostics report from Homey? Then I can see a bit more about what information I get.

**Comment by Retrospected** [comment]
Hey Edwin, 

Thanks for the quick response. I don't think there will be a lot of difference since technically it should be just a rebrand. I don't have any 'official' documentation unfortunately but i was building a [Brel Home Local app ](https://github.com/Retrospected/brel.home.local) myself based on these sources:

https://raw.githubusercontent.com/alexbacchin/ConnectorBridge/990c2bcf55967b27f7def01ce363c39012f5b86a/doc/Wi-Fi%20Local%20Access/Connector%20WLAN%20Integration%20Protocol.pdf
https://github.com/starkillerOG/motion-blinds/
https://gitlab.com/rogiervandergeer/brelpy

The latter is the only "brel specific" implementation i could find, however it does not support Heartbeat.

I dropped developing the brel local app since i discovered MotionBlinds are pretty much the same and your app is far more advanced 😄. But I'm happy to help where needed.

I have enabled full logging in the app.

**Comment by EDelsman** [comment]
The documentation looks the same, but also mentions the heartbeat data with the number of devices. Did you register a device yet?
Please also send me a diagnostics report form the Homey app if you can, then I can see the logging.
I will post a test version that protects from the missing data, but I'd rather see some more of the logging.

**Comment by EDelsman** [comment]
I posted a test version in the test channel of the homey app store that
checks for the missing data element. can ou check if that works and send me
a diagnostics report from the Homey app when it doesn’t?--
Groeten, Edwin

**Comment by Retrospected** [comment]
Seems to work just fine now. I can add&control the blinds and the app does not crash within 5minuten after starting anymore.

Incase it crashes i will send the diag report and will let you know! Thanks for the quick fix!
